### ISSUE TITLE
Incompatible signatures of Psym\Shell::reset() and Symfony\Component\Console\Application::reset(): void

### ISSUE THREAD

**Issue by smnscp** [tareqas/psym#1]
Starting Psym in a Symfony 7.1.5 app under PHP 8.3.11 results in a fatal error:

> PHP Fatal error:  Declaration of TareqAS\Psym\Shell::reset() must be compatible with Symfony\Component\Console\Application::reset(): void in […]/psym/src/Shell.php on line 37

Adding the return type `void` to [the function declaration](https://github.com/tareqas/psym/blob/main/src/Shell.php#L37) fixed it for me:
```php
    public function reset(): void
```

I did not test in other PHP 8 versions but AFAICT this will be a problem starting with PHP 8.0. Fortunately, [the `void` return type is supported as of PHP 7.1.0](https://www.php.net/manual/en/language.types.void.php), so it can be added here without breaking backwards compatibility.

**Comment by smnscp** [comment]
The problem is that it would break backwards compatibility with older Symfony versions that still have the [signature without return type](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Console/Application.php#L333).

**Comment by tareqas** [comment]
This issue has been fixed. https://github.com/tareqas/psym/commit/c799596bb5e96fe0c8900f97a52e738f5af6c6ce
Thank you.
